### PR TITLE
Working on comments for DrawArrowsView.

### PR DESCRIPTION
**Pull request by jamessentell**
Worked on the comments for the DrawArrowsView class - wanted to show you my progress so far.  There aren't any changes to the actual code in here - I just added comments for now.  Don't feel like you have to "accept" this merge request (in fact, probably better if you don't - see "P.S." below).  I honestly just wanted to try out Github's pull request feature!

P.S. No big deal, but do a "git add" on the fbd_2_greyed.xml drawable.  It is referenced in the code but isn't in the git repo, so it won't be in this pull request and the project won't build.

### CODE REVIEW

**Comment by ChrisGaddes** [comment]
Thanks so much James! I just added fbd_2_greyed.xml to git, thanks for catching that!
I tagged a bunch of notes with your name, but you by no means have to do anything with them cause i know you're busy!

**Comment by ChrisGaddes** [comment]
Also, the TODO's without your name are simply notes to myself and things I believe I can probably solve fairly easy I just haven't reached them yet

**Comment by jamessentell** [comment]
Sorry, wasn't entirely clear there.  You should keep the declaration outside the constructor (where you had it) but put the initialization inside the constructor.  For example:

``` java
public SomeClass {
    // Member variable declarations
    private int someMemberVariable;
    private ArrayList<int> arrayList;

    // Constructor - called whenever you create a "new" object of this class type  (SomeClass obj = new SomeClass();)
    public SomeClass() {
        // Initialize the member variable(s)
        this.someMemberVariable = 1000;
        this.arrayList = new ArrayList<int>();
    }
}
```

The way you had it before would work fine, so its up to you.  The compiled bytecode would probably be close to the same if not exactly the same.  This way just makes the timing and ordering of initialization more clear, in my opinion, since it is the constructor's job to initialize an instance of a class (including all its member variables if they require initialization).  Now, if you ever need to do `static` anything, its going to be different.  This just applies to instance variables (like the ones you are using).

**Comment by ChrisGaddes** [comment]
Thanks, but I'm still confused. I believe in my code I initialize the arraylists in setButtonPoints(Context context) which is run once.

`// Adds angles to the list of "correct" angles
        int btn = 0;
        angleListCheck.add(new ArrayList<Double>());
        angleListCheck.add(new ArrayList<Double>());
        angleListCheck.add(new ArrayList<Double>());
        angleListCheck.get(btn).add(0.0);
        angleListCheck.get(btn).add(-pi);
        angleListCheck.get(btn).add(pi / 2);
        angleListCheck.get(btn).add(-pi / 2);`

 I couldn't figure out a way to initialize it inside the DrawArrowsView constructor since the values in the pointList aarry are dependent on the width and height of the view which isn't known until the DrawArrowsView constructor is already run. I would like to use the best practices possible, what should I do about this?

**Comment by jamessentell** [comment]
Ah, gotcha.  I think that part of the code is fine.  I was only talking about the private/public member variables for the DrawArrowsView class on lines 84-91:

``` java
private ArrayList<Point> pointList = new ArrayList<>();
List<List<Double>> angleListCheck = new ArrayList<>();
private ArrayList<Rect> rectListButtons = new ArrayList<>();
private ArrayList<Rect> rectListArrowHead = new ArrayList<>();
private ArrayList<Path> pathList = new ArrayList<>();
private ArrayList<Point> pointListArrowHead = new ArrayList<>();
private ArrayList<Double> angleListArrowHead = new ArrayList<>();
private ArrayList<Integer> linkList = new ArrayList<>();
```

Here is what I was I meant:

``` java
public class DrawArrowsView extends ImageView {
    // Skipping a few lines...
    private ArrayList<Point> pointList;
    List<List<Double>> angleListCheck;
    private ArrayList<Rect> rectListButtons;
    private ArrayList<Rect> rectListArrowHead;
    private ArrayList<Path> pathList;
    private ArrayList<Point> pointListArrowHead;
    private ArrayList<Double> angleListArrowHead;
    private ArrayList<Integer> linkList;

   // Skip some more...
    public DrawArrowsView(Context context, AttributeSet attrs) {
        // ...
        this.pointList = new ArrayList<Point>();
        this.angleListCheck = new List<List<Double>>();
        this.rectLIstButtons = new ArrayList<Rect>();
       // So on...
    }
}
```

All your other initialization stuff and uses of the new keyword looked fine.

**Comment by ChrisGaddes** [comment]
That makes perfect sense, thanks! One question, is it necessary to place "this" in front?

`this.pointList = new ArrayList<Point>();`

VS.

`pointList = new ArrayList<Point>();`

**Comment by jamessentell** [comment]
Good!  No, its not really necessary.  I just use it out of habit because you had to use it to get to the auto complete menu to come up in some older ide's.  Definitely your preference!

**Comment by ChrisGaddes** [comment]
Thanks for the clarification! I really appreciate your help James, you're the man!

**Pull request closed without merging**
